version: '3.7'

services:
  paymentservice:
    container_name: ConfigurationService
    image: saireddyavs/spring_central_config_server
    ports:
      - "8888:8888"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
